package com.bill99.acs.gun.entity;

public class RoleResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gun_role_resource.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gun_role_resource.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gun_role_resource.resource_id
     *
     * @mbg.generated
     */
    private Long resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gun_role_resource.id
     *
     * @return the value of t_gun_role_resource.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gun_role_resource.id
     *
     * @param id the value for t_gun_role_resource.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gun_role_resource.role_id
     *
     * @return the value of t_gun_role_resource.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gun_role_resource.role_id
     *
     * @param roleId the value for t_gun_role_resource.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gun_role_resource.resource_id
     *
     * @return the value of t_gun_role_resource.resource_id
     *
     * @mbg.generated
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gun_role_resource.resource_id
     *
     * @param resourceId the value for t_gun_role_resource.resource_id
     *
     * @mbg.generated
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }
}